sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script:
  - echo "MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=256m'" > ~/.mavenrc
after_success:
  - mvn clean cobertura:cobertura coveralls:report
script: sh travis-run-tests.sh